spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: req413524
mybatis:
  mapper-locations: classpath:mapper/*.xml